// code management const
export const GETCODEMANAGEMENT = "GETCODEMANAGEMENT"
export const CREATECODEMANAGEMENT = "CREATECODEMANAGEMENT";
export const UPDATECODEMANAGEMENT = "UPDATECODEMANAGEMENT"
export const DELETECODEMANAGEMENT = "DELETECODEMANAGEMENT";

// creators const
export const GETCREATOR = "GETCREATOR"
export const CREATECREATOR = "CREATECREATOR";
export const UPDATECREATOR = "UPDATECREATOR"
export const DELETECREATOR = "DELETECREATOR";
export const GETSINGLECREATOR = "GETSINGLECREATOR"

// game metrics constant
export const GETGAMETRICS = "GETGAMETRICS"
export const CREATEGAMETRICS = "CREATEGAMETRICS";
export const UPDATEGAMETRICS = "UPDATEGAMETRICS"
export const DELETEGAMETRICS = "DELETEGAMETRICS";
export const GETSINGLEGAMETRICS = "GETSINGLEGAMETRICS"

// kyc const
export const GETKYC = "GETKYC"
export const CREATEKYC = "CREATEKYC";
export const UPDATEKYC = "UPDATEKYC"
export const DELETEKYC = "DELETEKYC";
export const GETSINGLEKYC = "GETSINGLEKYC"


// Withdrawal management const
export const GETWITHDRAWALMANAGEMENT = "GETWITHDRAWALMANAGEMENT"
export const CREATEWITHDRAWALMANAGEMENT = "CREATEWITHDRAWALMANAGEMENT";
export const UPDATEWITHDRAWALMANAGEMENT = "UPDATEWITHDRAWALMANAGEMENT"
export const DELETEWITHDRAWALMANAGEMENT = "DELETEWITHDRAWALMANAGEMENT";
export const GETSINGLEWITHDRAWALMANAGEMENT = "GETSINGLEWITHDRAWALMANAGEMENT"
