export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING"
export const PAGE_ERROR = "PAGE_ERROR"
// for admin
export const CREATEADMIN = "CREATEADMIN";
export const FETCHADMIN = "FETCHADMIN"
export const UPDATEADMIN = "UPDATEADMIN"
export const DELETEADMIN = "DELETEADMIN"

// payout
export const GETPAYOUT = "GETPAYOUT"
export const CREATEPAYOUT = "CREATEPAYOUT";
export const UPDATEPAYOUT = "UPDATEPAYOUT"
export const DELETEPAYOUT = "DELETEPAYOUT";

export const GETSINGLEPAYOUT = "GETSINGLEPAYOUT"
export const GETSUCCESS = "Successful"
export const GETFAILED = "Pending"
export const GETPENDING = "Failed"

// page management const
export const GETPAGEMANAGE = "GETPAGEMANAGE"
export const CREATEPAGEMANAGE = "CREATEPAGEMANAGE";
export const UPDATEPAGEMANAGE = "UPDATEPAGEMANAGE"
export const DELETEPAGEMANAGE = "DELETEPAGEMANAGE";
export const STATUSACTIVE = "Active";
export const STATUSPROCESSING = "Processing";
export const STATUSPENDING = "Pending";

// report const
export const GETREPORT = "GETREPORT"
export const CREATEREPORT = "CREATEREPORT";
export const UPDATEREPORT = "UPDATEREPORT"
export const DELETEREPORT = "DELETEREPORT";

// Sale constant
export const GETSALES = "GETSALES"
export const CREATESALES = "CREATESALES";
export const UPDATESALES = "UPDATESALES"
export const DELETESALES = "DELETESALES";

// Revenue constant
export const GETREVENUE = "GETREVENUE"
export const CREATEREVENUE = "CREATEREVENUE";
export const UPDATEREVENUE = "UPDATEREVENUE"
export const DELETEREVENUE = "DELETEREVENUE";

// code management const
export const GETCODEMANAGEMENT = "GETCODEMANAGEMENT"
export const CREATECODEMANAGEMENT = "CREATECODEMANAGEMENT";
export const UPDATECODEMANAGEMENT = "UPDATECODEMANAGEMENT"
export const DELETECODEMANAGEMENT = "DELETECODEMANAGEMENT";

// creators const
export const GETCREATOR = "GETCREATOR"
export const CREATECREATOR = "CREATECREATOR";
export const UPDATECREATOR = "UPDATECREATOR"
export const DELETECREATOR = "DELETECREATOR";
export const GETSINGLECREATOR = "GETSINGLECREATOR"

// game metrics constant
export const GETGAMETRICS = "GETGAMETRICS"
export const CREATEGAMETRICS = "CREATEGAMETRICS";
export const UPDATEGAMETRICS = "UPDATEGAMETRICS"
export const DELETEGAMETRICS = "DELETEGAMETRICS";
export const GETSINGLEGAMETRICS = "GETSINGLEGAMETRICS"

// kyc const
export const GETKYC = "GETKYC"
export const CREATEKYC = "CREATEKYC";
export const UPDATEKYC = "UPDATEKYC"
export const DELETEKYC = "DELETEKYC";
export const GETSINGLEKYC = "GETSINGLEKYC"


// Withdrawal management const
export const GETWITHDRAWALMANAGEMENT = "GETWITHDRAWALMANAGEMENT"
export const CREATEWITHDRAWALMANAGEMENT = "CREATEWITHDRAWALMANAGEMENT";
export const UPDATEWITHDRAWALMANAGEMENT = "UPDATEWITHDRAWALMANAGEMENT"
export const DELETEWITHDRAWALMANAGEMENT = "DELETEWITHDRAWALMANAGEMENT";
export const GETSINGLEWITHDRAWALMANAGEMENT = "GETSINGLEWITHDRAWALMANAGEMENT"

// users const
export const GETUSER = "GETUSER"
export const CREATEUSER = "CREATEUSER";
export const UPDATEUSER = "UPDATEUSER"
export const DELETEUSER = "DELETEUSER";
export const GETSINGLEUSER = "GETSINGLEUSER"