// users const
export const GETUSER = "GETUSER"
export const CREATEUSER = "CREATEUSER";
export const UPDATEUSER = "UPDATEUSER"
export const DELETEUSER = "DELETEUSER";
export const GETSINGLEUSER = "GETSINGLEUSER"

// kyc const
export const GETUSERKYC = "GETUSERKYC"
export const CREATEUSERKYC = "CREATEUSERKYC";
export const UPDATEUSERKYC = "UPDATEUSERKYC"
export const DELETEUSERKYC = "DELETEUSERKYC";
export const GETSINGLEUSERKYC = "GETSINGLEUSERKYC"


// Withdrawal management const
export const GETUSERWITHDRAWALMANAGEMENT = "GETUSERWITHDRAWALMANAGEMENT"
export const CREATEUSERWITHDRAWALMANAGEMENT = "CREATEUSERWITHDRAWALMANAGEMENT";
export const UPDATEUSERWITHDRAWALMANAGEMENT = "UPDATEUSERWITHDRAWALMANAGEMENT"
export const DELETEUSERWITHDRAWALMANAGEMENT = "DELETEUSERWITHDRAWALMANAGEMENT";
export const GETSINGLEUSERWITHDRAWALMANAGEMENT = "GETSINGLEUSERWITHDRAWALMANAGEMENT"