// for admin
export const CREATEADMIN = "CREATEADMIN";
export const FETCHADMIN = "FETCHADMIN"
export const UPDATEADMIN = "UPDATEADMIN"
export const DELETEADMIN = "DELETEADMIN"

// payout
export const GETPAYOUT = "GETPAYOUT"
export const CREATEPAYOUT = "CREATEPAYOUT";
export const UPDATEPAYOUT = "UPDATEPAYOUT"
export const DELETEPAYOUT = "DELETEPAYOUT";

export const GETSINGLE = "GETSINGLE"

// page management const
export const GETPAGEMANAGE = "GETPAGEMANAGE"
export const CREATEPAGEMANAGE = "CREATEPAGEMANAGE";
export const UPDATEPAGEMANAGE = "UPDATEPAGEMANAGE"
export const DELETEPAGEMANAGE = "DELETEPAGEMANAGE";

// report const
export const GETREPORT = "GETREPORT"
export const CREATEREPORT = "CREATEREPORT";
export const UPDATEREPORT = "UPDATEREPORT"
export const DELETEREPORT = "DELETEREPORT";